### ISSUE TITLE
StreamDecoder : _le_chunks_ undefined

### ISSUE THREAD

**Issue by soufi** [melchor629/node-flac-bindings#1]
Hi there,

I am using this library to decode a flac stream recovered from a WebSocket. 

When I pipe the flac stream into the decoder. I have the following error : 

> /node_modules/flac-bindings/lib/decoder.js:79
        this._le_chunks[0].copy(buffer);
                      ^
> 
> TypeError: Cannot read property '0' of undefined

The flac stream was originally encoded using this module. Do you have any idea on how to resolve this ?

**Comment by melchor629** [comment]
Thanks for reporting the error. I have to say that this class, `StreamDecoder`, has not been tested, so it was really incomplete and bugged. Now it should work pretty well. I will push the changes to npm.
