### ISSUE TITLE
how to create metadata

### ISSUE THREAD

**Issue by smoebody** [melchor629/node-flac-bindings#3]
hello @melchor629, can you give a short example how to create a new metadata block and write it to a new flac-file?

**Comment by melchor629** [comment]
The Metadata functions and APIs are not completed. I'm working on it to implement them. Meanwhile, I recommend you to read the [metadata](https://xiph.org/flac/api/group__flac__metadata__object.html) and [simple iterator](https://xiph.org/flac/api/group__flac__metadata__level1.html) documentation to give you an idea of what to do. When this part of the bindings is completed, I will write the documentation in the Wiki and put some examples of that also in the Wiki.

**Comment by melchor629** [comment]
I released a new version with the Metadata APIs working (I expect) and I wrote a guide about how to use these APIs [in the Wiki](https://github.com/melchor629/node-flac-bindings/wiki/using-metadata-apis-with-the-bindings). At the end of the page, you will found an example of a test I did that inserts a metadata block and modifies another already created using the level 1 API. Pay attention to the notes in the guide.

I expect with that, you can resolve your issue now.

**Comment by smoebody** [comment]
thanks alot! i will have a look at it soonish

**Comment by melchor629** [comment]
Nice :)

I'm closing the issue.
